"""add schemas

Revision ID: 461371575299
Revises: 687465b3b8f1
Create Date: 2020-02-09 19:46:09.281817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461371575299'
down_revision = '687465b3b8f1'
branch_labels = None
depends_on = None

schemas_names = ['cbs', 'news_flash', 'schools', 'mobile_app']

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for schema_name in schemas_names:
        cmd = "CREATE SCHEMA IF NOT EXISTS " + schema_name
        op.execute(cmd)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for schema_name in schemas_names:
        cmd = "DROP SCHEMA IF EXISTS " + schema_name
        op.execute(cmd)
    # ### end Alembic commands ###
