"""production models

Revision ID: 528b5b1526c3
Revises: 461371575299
Create Date: 2020-02-10 14:35:21.718470

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '528b5b1526c3'
down_revision = '461371575299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accident_hour_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('accident_hour_raw_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_accident_hour_raw_id'), 'accident_hour_raw', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_accident_hour_raw_provider_code'), 'accident_hour_raw', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_accident_hour_raw_year'), 'accident_hour_raw', ['year'], unique=False, schema='cbs')
    op.create_table('accident_month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('accident_month_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_accident_month_id'), 'accident_month', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_accident_month_provider_code'), 'accident_month', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_accident_month_year'), 'accident_month', ['year'], unique=False, schema='cbs')
    op.create_table('accident_severity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('accident_severity_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_accident_severity_id'), 'accident_severity', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_accident_severity_provider_code'), 'accident_severity', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_accident_severity_year'), 'accident_severity', ['year'], unique=False, schema='cbs')
    op.create_table('accident_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('accident_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_accident_type_id'), 'accident_type', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_accident_type_provider_code'), 'accident_type', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_accident_type_year'), 'accident_type', ['year'], unique=False, schema='cbs')
    op.create_table('age_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('age_group_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_age_group_id'), 'age_group', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_age_group_provider_code'), 'age_group', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_age_group_year'), 'age_group', ['year'], unique=False, schema='cbs')
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('search_heb', sa.String(), nullable=True),
    sa.Column('search_eng', sa.String(), nullable=True),
    sa.Column('search_priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cbs'
    )
    op.create_table('cities_vehicles_registered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_eng', sa.String(), nullable=True),
    sa.Column('search_name', sa.String(), nullable=True),
    sa.Column('motorcycle', sa.Integer(), nullable=True),
    sa.Column('special', sa.Integer(), nullable=True),
    sa.Column('taxi', sa.Integer(), nullable=True),
    sa.Column('bus', sa.Integer(), nullable=True),
    sa.Column('minibus', sa.Integer(), nullable=True),
    sa.Column('truck_over3500', sa.Integer(), nullable=True),
    sa.Column('truck_upto3500', sa.Integer(), nullable=True),
    sa.Column('private', sa.Integer(), nullable=True),
    sa.Column('population_year', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cbs'
    )
    op.create_table('columns_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('column_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_columns_description_id'), 'columns_description', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_columns_description_provider_code'), 'columns_description', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_columns_description_year'), 'columns_description', ['year'], unique=False, schema='cbs')
    op.create_table('cross_direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('cross_direction_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_cross_direction_id'), 'cross_direction', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_cross_direction_provider_code'), 'cross_direction', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_cross_direction_year'), 'cross_direction', ['year'], unique=False, schema='cbs')
    op.create_table('cross_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('cross_location_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_cross_location_id'), 'cross_location', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_cross_location_provider_code'), 'cross_location', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_cross_location_year'), 'cross_location', ['year'], unique=False, schema='cbs')
    op.create_table('cross_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('cross_mode_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_cross_mode_id'), 'cross_mode', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_cross_mode_provider_code'), 'cross_mode', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_cross_mode_year'), 'cross_mode', ['year'], unique=False, schema='cbs')
    op.create_table('day_in_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('day_in_week_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_day_in_week_id'), 'day_in_week', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_day_in_week_provider_code'), 'day_in_week', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_day_in_week_year'), 'day_in_week', ['year'], unique=False, schema='cbs')
    op.create_table('day_night',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('day_night_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_day_night_id'), 'day_night', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_day_night_provider_code'), 'day_night', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_day_night_year'), 'day_night', ['year'], unique=False, schema='cbs')
    op.create_table('day_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('day_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_day_type_id'), 'day_type', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_day_type_provider_code'), 'day_type', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_day_type_year'), 'day_type', ['year'], unique=False, schema='cbs')
    op.create_table('didnt_cross',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('didnt_cross_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_didnt_cross_id'), 'didnt_cross', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_didnt_cross_provider_code'), 'didnt_cross', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_didnt_cross_year'), 'didnt_cross', ['year'], unique=False, schema='cbs')
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier'),
    schema='cbs'
    )
    op.create_index('disc_long_lat_idx', 'discussions', ['latitude', 'longitude'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_discussions_created'), 'discussions', ['created'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_discussions_geom'), 'discussions', ['geom'], unique=False, schema='cbs')
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('district_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_district_id'), 'district', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_district_provider_code'), 'district', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_district_year'), 'district', ['year'], unique=False, schema='cbs')
    op.create_table('driving_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('driving_directions_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_driving_directions_id'), 'driving_directions', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_driving_directions_provider_code'), 'driving_directions', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_driving_directions_year'), 'driving_directions', ['year'], unique=False, schema='cbs')
    op.create_table('engine_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('engine_volume_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_engine_volume_id'), 'engine_volume', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_engine_volume_provider_code'), 'engine_volume', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_engine_volume_year'), 'engine_volume', ['year'], unique=False, schema='cbs')
    op.create_table('geo_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('geo_area_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_geo_area_id'), 'geo_area', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_geo_area_provider_code'), 'geo_area', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_geo_area_year'), 'geo_area', ['year'], unique=False, schema='cbs')
    op.create_table('hospital_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('hospital_time_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_hospital_time_id'), 'hospital_time', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_hospital_time_provider_code'), 'hospital_time', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_hospital_time_year'), 'hospital_time', ['year'], unique=False, schema='cbs')
    op.create_table('injured_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('injured_position_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_injured_position_id'), 'injured_position', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_injured_position_provider_code'), 'injured_position', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_injured_position_year'), 'injured_position', ['year'], unique=False, schema='cbs')
    op.create_table('injured_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('injured_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_injured_type_id'), 'injured_type', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_injured_type_provider_code'), 'injured_type', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_injured_type_year'), 'injured_type', ['year'], unique=False, schema='cbs')
    op.create_table('injury_severity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('injury_severity_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_injury_severity_id'), 'injury_severity', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_injury_severity_provider_code'), 'injury_severity', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_injury_severity_year'), 'injury_severity', ['year'], unique=False, schema='cbs')
    op.create_table('involved_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('involved_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_involved_type_id'), 'involved_type', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_involved_type_provider_code'), 'involved_type', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_involved_type_year'), 'involved_type', ['year'], unique=False, schema='cbs')
    op.create_table('late_deceased',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('late_deceased_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_late_deceased_id'), 'late_deceased', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_late_deceased_provider_code'), 'late_deceased', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_late_deceased_year'), 'late_deceased', ['year'], unique=False, schema='cbs')
    op.create_table('location_accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('location_accuracy_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_location_accuracy_id'), 'location_accuracy', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_location_accuracy_provider_code'), 'location_accuracy', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_location_accuracy_year'), 'location_accuracy', ['year'], unique=False, schema='cbs')
    op.create_table('markers',
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_and_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('file_type_police', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accident_type', sa.Integer(), nullable=True),
    sa.Column('accident_severity', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location_accuracy', sa.Integer(), nullable=True),
    sa.Column('road_type', sa.Integer(), nullable=True),
    sa.Column('road_shape', sa.Integer(), nullable=True),
    sa.Column('day_type', sa.Integer(), nullable=True),
    sa.Column('police_unit', sa.Integer(), nullable=True),
    sa.Column('mainStreet', sa.Text(), nullable=True),
    sa.Column('secondaryStreet', sa.Text(), nullable=True),
    sa.Column('junction', sa.Text(), nullable=True),
    sa.Column('one_lane', sa.Integer(), nullable=True),
    sa.Column('multi_lane', sa.Integer(), nullable=True),
    sa.Column('speed_limit', sa.Integer(), nullable=True),
    sa.Column('road_intactness', sa.Integer(), nullable=True),
    sa.Column('road_width', sa.Integer(), nullable=True),
    sa.Column('road_sign', sa.Integer(), nullable=True),
    sa.Column('road_light', sa.Integer(), nullable=True),
    sa.Column('road_control', sa.Integer(), nullable=True),
    sa.Column('weather', sa.Integer(), nullable=True),
    sa.Column('road_surface', sa.Integer(), nullable=True),
    sa.Column('road_object', sa.Integer(), nullable=True),
    sa.Column('object_distance', sa.Integer(), nullable=True),
    sa.Column('didnt_cross', sa.Integer(), nullable=True),
    sa.Column('cross_mode', sa.Integer(), nullable=True),
    sa.Column('cross_location', sa.Integer(), nullable=True),
    sa.Column('cross_direction', sa.Integer(), nullable=True),
    sa.Column('video_link', sa.Text(), nullable=True),
    sa.Column('road1', sa.Integer(), nullable=True),
    sa.Column('road2', sa.Integer(), nullable=True),
    sa.Column('km', sa.Float(), nullable=True),
    sa.Column('km_raw', sa.Text(), nullable=True),
    sa.Column('km_accurate', sa.Boolean(), nullable=True),
    sa.Column('yishuv_symbol', sa.Integer(), nullable=True),
    sa.Column('yishuv_name', sa.Text(), nullable=True),
    sa.Column('geo_area', sa.Integer(), nullable=True),
    sa.Column('day_night', sa.Integer(), nullable=True),
    sa.Column('day_in_week', sa.Integer(), nullable=True),
    sa.Column('traffic_light', sa.Integer(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('natural_area', sa.Integer(), nullable=True),
    sa.Column('municipal_status', sa.Integer(), nullable=True),
    sa.Column('yishuv_shape', sa.Integer(), nullable=True),
    sa.Column('street1', sa.Integer(), nullable=True),
    sa.Column('street1_hebrew', sa.Text(), nullable=True),
    sa.Column('street2', sa.Integer(), nullable=True),
    sa.Column('street2_hebrew', sa.Text(), nullable=True),
    sa.Column('house_number', sa.Integer(), nullable=True),
    sa.Column('urban_intersection', sa.Integer(), nullable=True),
    sa.Column('non_urban_intersection', sa.Integer(), nullable=True),
    sa.Column('non_urban_intersection_hebrew', sa.Text(), nullable=True),
    sa.Column('accident_year', sa.Integer(), nullable=False),
    sa.Column('accident_month', sa.Integer(), nullable=True),
    sa.Column('accident_day', sa.Integer(), nullable=True),
    sa.Column('accident_hour_raw', sa.Integer(), nullable=True),
    sa.Column('accident_hour', sa.Integer(), nullable=True),
    sa.Column('accident_minute', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('vehicle_type_rsa', sa.Text(), nullable=True),
    sa.Column('violation_type_rsa', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('non_urban_intersection_by_junction_number', sa.Text(), nullable=True),
    sa.Column('rsa_severity', sa.Integer(), nullable=True),
    sa.Column('rsa_license_plate', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'provider_code', 'accident_year'),
    schema='cbs'
    )
    op.create_index('acc_long_lat_idx', 'markers', ['latitude', 'longitude'], unique=False, schema='cbs')
    op.create_index('id_idx_markers', 'markers', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_markers_created'), 'markers', ['created'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_markers_geom'), 'markers', ['geom'], unique=False, schema='cbs')
    op.create_index('provider_and_id_idx_markers', 'markers', ['provider_and_id'], unique=False, schema='cbs')
    op.create_table('medical_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('medical_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_medical_type_id'), 'medical_type', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_medical_type_provider_code'), 'medical_type', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_medical_type_year'), 'medical_type', ['year'], unique=False, schema='cbs')
    op.create_table('multi_lane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('multi_lane_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_multi_lane_id'), 'multi_lane', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_multi_lane_provider_code'), 'multi_lane', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_multi_lane_year'), 'multi_lane', ['year'], unique=False, schema='cbs')
    op.create_table('municipal_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('municipal_status_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_municipal_status_id'), 'municipal_status', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_municipal_status_provider_code'), 'municipal_status', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_municipal_status_year'), 'municipal_status', ['year'], unique=False, schema='cbs')
    op.create_table('natural_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('natural_area_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_natural_area_id'), 'natural_area', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_natural_area_provider_code'), 'natural_area', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_natural_area_year'), 'natural_area', ['year'], unique=False, schema='cbs')
    op.create_table('object_distance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('object_distance_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_object_distance_id'), 'object_distance', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_object_distance_provider_code'), 'object_distance', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_object_distance_year'), 'object_distance', ['year'], unique=False, schema='cbs')
    op.create_table('one_lane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('one_lane_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_one_lane_id'), 'one_lane', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_one_lane_provider_code'), 'one_lane', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_one_lane_year'), 'one_lane', ['year'], unique=False, schema='cbs')
    op.create_table('police_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('police_unit_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_police_unit_id'), 'police_unit', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_police_unit_provider_code'), 'police_unit', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_police_unit_year'), 'police_unit', ['year'], unique=False, schema='cbs')
    op.create_table('population_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('population_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_population_type_id'), 'population_type', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_population_type_provider_code'), 'population_type', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_population_type_year'), 'population_type', ['year'], unique=False, schema='cbs')
    op.create_table('provider_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_provider_code_id'), 'provider_code', ['id'], unique=False, schema='cbs')
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('region_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_region_id'), 'region', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_region_provider_code'), 'region', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_region_year'), 'region', ['year'], unique=False, schema='cbs')
    op.create_table('release_dest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('release_dest_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_release_dest_id'), 'release_dest', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_release_dest_provider_code'), 'release_dest', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_release_dest_year'), 'release_dest', ['year'], unique=False, schema='cbs')
    op.create_table('road_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_control_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_road_control_id'), 'road_control', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_control_provider_code'), 'road_control', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_control_year'), 'road_control', ['year'], unique=False, schema='cbs')
    op.create_table('road_intactness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_intactness_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_road_intactness_id'), 'road_intactness', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_intactness_provider_code'), 'road_intactness', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_intactness_year'), 'road_intactness', ['year'], unique=False, schema='cbs')
    op.create_table('road_light',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_light_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_road_light_id'), 'road_light', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_light_provider_code'), 'road_light', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_light_year'), 'road_light', ['year'], unique=False, schema='cbs')
    op.create_table('road_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_object_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_road_object_id'), 'road_object', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_object_provider_code'), 'road_object', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_object_year'), 'road_object', ['year'], unique=False, schema='cbs')
    op.create_table('road_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('road', sa.Integer(), nullable=True),
    sa.Column('segment', sa.Integer(), nullable=True),
    sa.Column('from_km', sa.Float(), nullable=True),
    sa.Column('from_name', sa.Text(), nullable=True),
    sa.Column('to_km', sa.Float(), nullable=True),
    sa.Column('to_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cbs'
    )
    op.create_table('road_shape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_shape_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_road_shape_id'), 'road_shape', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_shape_provider_code'), 'road_shape', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_shape_year'), 'road_shape', ['year'], unique=False, schema='cbs')
    op.create_table('road_sign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_sign_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_road_sign_id'), 'road_sign', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_sign_provider_code'), 'road_sign', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_sign_year'), 'road_sign', ['year'], unique=False, schema='cbs')
    op.create_table('road_surface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_surface_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_road_surface_id'), 'road_surface', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_surface_provider_code'), 'road_surface', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_surface_year'), 'road_surface', ['year'], unique=False, schema='cbs')
    op.create_table('road_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_road_type_id'), 'road_type', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_type_provider_code'), 'road_type', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_type_year'), 'road_type', ['year'], unique=False, schema='cbs')
    op.create_table('road_width',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_width_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_road_width_id'), 'road_width', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_width_provider_code'), 'road_width', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_road_width_year'), 'road_width', ['year'], unique=False, schema='cbs')
    op.create_table('safety_measures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('safety_measures_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_safety_measures_id'), 'safety_measures', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_safety_measures_provider_code'), 'safety_measures', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_safety_measures_year'), 'safety_measures', ['year'], unique=False, schema='cbs')
    op.create_table('safety_measures_use',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('safety_measures_use_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_safety_measures_use_id'), 'safety_measures_use', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_safety_measures_use_provider_code'), 'safety_measures_use', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_safety_measures_use_year'), 'safety_measures_use', ['year'], unique=False, schema='cbs')
    op.create_table('sex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('sex_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_sex_id'), 'sex', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_sex_provider_code'), 'sex', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_sex_year'), 'sex', ['year'], unique=False, schema='cbs')
    op.create_table('speed_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('speed_limit_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_speed_limit_id'), 'speed_limit', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_speed_limit_provider_code'), 'speed_limit', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_speed_limit_year'), 'speed_limit', ['year'], unique=False, schema='cbs')
    op.create_table('total_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('total_weight_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_total_weight_id'), 'total_weight', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_total_weight_provider_code'), 'total_weight', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_total_weight_year'), 'total_weight', ['year'], unique=False, schema='cbs')
    op.create_table('traffic_light',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('traffic_light_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_traffic_light_id'), 'traffic_light', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_traffic_light_provider_code'), 'traffic_light', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_traffic_light_year'), 'traffic_light', ['year'], unique=False, schema='cbs')
    op.create_table('traffic_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('road', sa.Integer(), nullable=True),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_traffic_volume_id'), 'traffic_volume', ['id'], unique=False, schema='cbs')
    op.create_table('vehicle_attribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('vehicle_attribution_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_vehicle_attribution_id'), 'vehicle_attribution', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_vehicle_attribution_provider_code'), 'vehicle_attribution', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_vehicle_attribution_year'), 'vehicle_attribution', ['year'], unique=False, schema='cbs')
    op.create_table('vehicle_damage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('vehicle_damage_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_vehicle_damage_id'), 'vehicle_damage', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_vehicle_damage_provider_code'), 'vehicle_damage', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_vehicle_damage_year'), 'vehicle_damage', ['year'], unique=False, schema='cbs')
    op.create_table('vehicle_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('vehicle_status_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_vehicle_status_id'), 'vehicle_status', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_vehicle_status_provider_code'), 'vehicle_status', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_vehicle_status_year'), 'vehicle_status', ['year'], unique=False, schema='cbs')
    op.create_table('vehicle_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_vehicle_type_id'), 'vehicle_type', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_vehicle_type_provider_code'), 'vehicle_type', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_vehicle_type_year'), 'vehicle_type', ['year'], unique=False, schema='cbs')
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('weather_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_weather_id'), 'weather', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_weather_provider_code'), 'weather', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_weather_year'), 'weather', ['year'], unique=False, schema='cbs')
    op.create_table('yishuv_shape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('yishuv_shape_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code'),
    schema='cbs'
    )
    op.create_index(op.f('ix_cbs_yishuv_shape_id'), 'yishuv_shape', ['id'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_yishuv_shape_provider_code'), 'yishuv_shape', ['provider_code'], unique=False, schema='cbs')
    op.create_index(op.f('ix_cbs_yishuv_shape_year'), 'yishuv_shape', ['year'], unique=False, schema='cbs')
    op.create_table('involved',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_and_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_code', sa.Integer(), nullable=True),
    sa.Column('file_type_police', sa.Integer(), nullable=True),
    sa.Column('accident_id', sa.BigInteger(), nullable=True),
    sa.Column('involved_type', sa.Integer(), nullable=True),
    sa.Column('license_acquiring_date', sa.Integer(), nullable=True),
    sa.Column('age_group', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('safety_measures', sa.Integer(), nullable=True),
    sa.Column('involve_yishuv_symbol', sa.Integer(), nullable=True),
    sa.Column('involve_yishuv_name', sa.Text(), nullable=True),
    sa.Column('injury_severity', sa.Integer(), nullable=True),
    sa.Column('injured_type', sa.Integer(), nullable=True),
    sa.Column('injured_position', sa.Integer(), nullable=True),
    sa.Column('population_type', sa.Integer(), nullable=True),
    sa.Column('home_region', sa.Integer(), nullable=True),
    sa.Column('home_district', sa.Integer(), nullable=True),
    sa.Column('home_natural_area', sa.Integer(), nullable=True),
    sa.Column('home_municipal_status', sa.Integer(), nullable=True),
    sa.Column('home_yishuv_shape', sa.Integer(), nullable=True),
    sa.Column('hospital_time', sa.Integer(), nullable=True),
    sa.Column('medical_type', sa.Integer(), nullable=True),
    sa.Column('release_dest', sa.Integer(), nullable=True),
    sa.Column('safety_measures_use', sa.Integer(), nullable=True),
    sa.Column('late_deceased', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('involve_id', sa.Integer(), nullable=True),
    sa.Column('accident_year', sa.Integer(), nullable=True),
    sa.Column('accident_month', sa.Integer(), nullable=True),
    sa.Column('injury_severity_mais', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accident_id', 'provider_code', 'accident_year'], ['cbs.markers.id', 'cbs.markers.provider_code', 'cbs.markers.accident_year'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cbs'
    )
    op.create_index('accident_id_idx_involved', 'involved', ['accident_id'], unique=False, schema='cbs')
    op.create_index('provider_and_id_idx_involved', 'involved', ['provider_and_id'], unique=False, schema='cbs')
    op.create_table('vehicles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_and_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_code', sa.Integer(), nullable=True),
    sa.Column('file_type_police', sa.Integer(), nullable=True),
    sa.Column('accident_id', sa.BigInteger(), nullable=True),
    sa.Column('engine_volume', sa.Integer(), nullable=True),
    sa.Column('manufacturing_year', sa.Integer(), nullable=True),
    sa.Column('driving_directions', sa.Integer(), nullable=True),
    sa.Column('vehicle_status', sa.Integer(), nullable=True),
    sa.Column('vehicle_attribution', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('total_weight', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('accident_year', sa.Integer(), nullable=True),
    sa.Column('accident_month', sa.Integer(), nullable=True),
    sa.Column('vehicle_damage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accident_id', 'provider_code', 'accident_year'], ['cbs.markers.id', 'cbs.markers.provider_code', 'cbs.markers.accident_year'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cbs'
    )
    op.create_index('accident_id_idx_vehicles', 'vehicles', ['accident_id'], unique=False, schema='cbs')
    op.create_index('provider_and_id_idx_vehicles', 'vehicles', ['provider_and_id'], unique=False, schema='cbs')
    op.create_table('news_flash',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('accident', sa.Boolean(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('road1', sa.Float(), nullable=True),
    sa.Column('road2', sa.Float(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('tweet_id', sa.BigInteger(), nullable=True),
    sa.Column('region_hebrew', sa.Text(), nullable=True),
    sa.Column('district_hebrew', sa.Text(), nullable=True),
    sa.Column('yishuv_name', sa.Text(), nullable=True),
    sa.Column('street1_hebrew', sa.Text(), nullable=True),
    sa.Column('street2_hebrew', sa.Text(), nullable=True),
    sa.Column('non_urban_intersection_hebrew', sa.Text(), nullable=True),
    sa.Column('road_segment_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='news_flash'
    )
    op.create_table('injured_around_school',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.Text(), nullable=True),
    sa.Column('school_type', sa.Text(), nullable=True),
    sa.Column('school_longitude', sa.Float(), nullable=True),
    sa.Column('school_latitude', sa.Float(), nullable=True),
    sa.Column('school_yishuv_name', sa.Text(), nullable=True),
    sa.Column('school_anyway_link', sa.Text(), nullable=True),
    sa.Column('accident_year', sa.Integer(), nullable=True),
    sa.Column('distance_in_km', sa.Float(), nullable=True),
    sa.Column('killed_count', sa.Integer(), nullable=True),
    sa.Column('severly_injured_count', sa.Integer(), nullable=True),
    sa.Column('light_injured_count', sa.Integer(), nullable=True),
    sa.Column('total_injured_killed_count', sa.Integer(), nullable=True),
    sa.Column('rank_in_yishuv', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='schools'
    )
    op.create_index(op.f('ix_schools_injured_around_school_id'), 'injured_around_school', ['id'], unique=False, schema='schools')
    op.create_index(op.f('ix_schools_injured_around_school_school_id'), 'injured_around_school', ['school_id'], unique=False, schema='schools')
    op.create_index(op.f('ix_schools_injured_around_school_school_yishuv_name'), 'injured_around_school', ['school_yishuv_name'], unique=False, schema='schools')
    op.create_table('injured_around_school_all_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Float(), nullable=False),
    sa.Column('markers_provider_and_id', sa.BigInteger(), nullable=True),
    sa.Column('markers_provider_code', sa.Float(), nullable=True),
    sa.Column('markers_description', sa.Text(), nullable=True),
    sa.Column('markers_accident_type', sa.Float(), nullable=True),
    sa.Column('markers_accident_severity', sa.Float(), nullable=True),
    sa.Column('markers_address', sa.Text(), nullable=True),
    sa.Column('markers_location_accuracy', sa.Float(), nullable=True),
    sa.Column('markers_road_type', sa.Float(), nullable=True),
    sa.Column('markers_road_shape', sa.Float(), nullable=True),
    sa.Column('markers_day_type', sa.Float(), nullable=True),
    sa.Column('markers_police_unit', sa.Float(), nullable=True),
    sa.Column('markers_mainStreet', sa.Text(), nullable=True),
    sa.Column('markers_secondaryStreet', sa.Text(), nullable=True),
    sa.Column('markers_junction', sa.Text(), nullable=True),
    sa.Column('markers_one_lane', sa.Float(), nullable=True),
    sa.Column('markers_multi_lane', sa.Float(), nullable=True),
    sa.Column('markers_speed_limit', sa.Float(), nullable=True),
    sa.Column('markers_road_intactness', sa.Float(), nullable=True),
    sa.Column('markers_road_width', sa.Float(), nullable=True),
    sa.Column('markers_road_sign', sa.Float(), nullable=True),
    sa.Column('markers_road_light', sa.Float(), nullable=True),
    sa.Column('markers_road_control', sa.Float(), nullable=True),
    sa.Column('markers_weather', sa.Float(), nullable=True),
    sa.Column('markers_road_surface', sa.Float(), nullable=True),
    sa.Column('markers_road_object', sa.Float(), nullable=True),
    sa.Column('markers_object_distance', sa.Float(), nullable=True),
    sa.Column('markers_didnt_cross', sa.Float(), nullable=True),
    sa.Column('markers_cross_mode', sa.Float(), nullable=True),
    sa.Column('markers_cross_location', sa.Float(), nullable=True),
    sa.Column('markers_cross_direction', sa.Float(), nullable=True),
    sa.Column('markers_video_link', sa.Text(), nullable=True),
    sa.Column('markers_road1', sa.Float(), nullable=True),
    sa.Column('markers_road2', sa.Float(), nullable=True),
    sa.Column('markers_km', sa.Float(), nullable=True),
    sa.Column('markers_yishuv_symbol', sa.Float(), nullable=True),
    sa.Column('markers_yishuv_name', sa.Text(), nullable=True),
    sa.Column('markers_geo_area', sa.Float(), nullable=True),
    sa.Column('markers_day_night', sa.Float(), nullable=True),
    sa.Column('markers_day_in_week', sa.Float(), nullable=True),
    sa.Column('markers_traffic_light', sa.Float(), nullable=True),
    sa.Column('markers_region', sa.Float(), nullable=True),
    sa.Column('markers_district', sa.Float(), nullable=True),
    sa.Column('markers_natural_area', sa.Float(), nullable=True),
    sa.Column('markers_municipal_status', sa.Float(), nullable=True),
    sa.Column('markers_yishuv_shape', sa.Float(), nullable=True),
    sa.Column('markers_street1', sa.Float(), nullable=True),
    sa.Column('markers_street1_hebrew', sa.Text(), nullable=True),
    sa.Column('markers_street2', sa.Float(), nullable=True),
    sa.Column('markers_street2_hebrew', sa.Text(), nullable=True),
    sa.Column('markers_house_number', sa.Float(), nullable=True),
    sa.Column('markers_urban_intersection', sa.Float(), nullable=True),
    sa.Column('markers_non_urban_intersection', sa.Float(), nullable=True),
    sa.Column('markers_non_urban_intersection_hebrew', sa.Text(), nullable=True),
    sa.Column('markers_accident_year', sa.Float(), nullable=True),
    sa.Column('markers_accident_month', sa.Float(), nullable=True),
    sa.Column('markers_accident_day', sa.Float(), nullable=True),
    sa.Column('markers_accident_hour_raw', sa.Float(), nullable=True),
    sa.Column('markers_accident_hour', sa.Float(), nullable=True),
    sa.Column('markers_accident_minute', sa.Float(), nullable=True),
    sa.Column('markers_x', sa.Float(), nullable=True),
    sa.Column('markers_y', sa.Float(), nullable=True),
    sa.Column('markers_vehicle_type_rsa', sa.Text(), nullable=True),
    sa.Column('markers_violation_type_rsa', sa.Text(), nullable=True),
    sa.Column('markers_geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('involved_provider_and_id', sa.BigInteger(), nullable=True),
    sa.Column('involved_provider_code', sa.Float(), nullable=True),
    sa.Column('involved_accident_id', sa.BigInteger(), nullable=True),
    sa.Column('involved_involved_type', sa.Float(), nullable=True),
    sa.Column('involved_license_acquiring_date', sa.Float(), nullable=True),
    sa.Column('involved_age_group', sa.Float(), nullable=True),
    sa.Column('involved_sex', sa.Float(), nullable=True),
    sa.Column('involved_vehicle_type', sa.Float(), nullable=True),
    sa.Column('involved_safety_measures', sa.Float(), nullable=True),
    sa.Column('involved_involve_yishuv_symbol', sa.Float(), nullable=True),
    sa.Column('involved_involve_yishuv_name', sa.Text(), nullable=True),
    sa.Column('involved_injury_severity', sa.Float(), nullable=True),
    sa.Column('involved_injured_type', sa.Float(), nullable=True),
    sa.Column('involved_injured_position', sa.Float(), nullable=True),
    sa.Column('involved_population_type', sa.Float(), nullable=True),
    sa.Column('involved_home_region', sa.Float(), nullable=True),
    sa.Column('involved_home_district', sa.Float(), nullable=True),
    sa.Column('involved_home_natural_area', sa.Float(), nullable=True),
    sa.Column('involved_home_municipal_status', sa.Float(), nullable=True),
    sa.Column('involved_home_yishuv_shape', sa.Float(), nullable=True),
    sa.Column('involved_hospital_time', sa.Float(), nullable=True),
    sa.Column('involved_medical_type', sa.Float(), nullable=True),
    sa.Column('involved_release_dest', sa.Float(), nullable=True),
    sa.Column('involved_safety_measures_use', sa.Float(), nullable=True),
    sa.Column('involved_late_deceased', sa.Float(), nullable=True),
    sa.Column('involved_car_id', sa.Float(), nullable=True),
    sa.Column('involved_involve_id', sa.Float(), nullable=True),
    sa.Column('involved_accident_year', sa.Float(), nullable=True),
    sa.Column('involved_accident_month', sa.Float(), nullable=True),
    sa.Column('involved_injury_severity_mais', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='schools'
    )
    op.create_index(op.f('ix_schools_injured_around_school_all_data_id'), 'injured_around_school_all_data', ['id'], unique=False, schema='schools')
    op.create_index(op.f('ix_schools_injured_around_school_all_data_school_id'), 'injured_around_school_all_data', ['school_id'], unique=False, schema='schools')
    op.create_table('schools',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fcode_type', sa.Integer(), nullable=True),
    sa.Column('yishuv_symbol', sa.Integer(), nullable=True),
    sa.Column('yishuv_name', sa.Text(), nullable=True),
    sa.Column('school_name', sa.Text(), nullable=True),
    sa.Column('school_latin_name', sa.Text(), nullable=True),
    sa.Column('usg', sa.Integer(), nullable=True),
    sa.Column('usg_code', sa.Integer(), nullable=True),
    sa.Column('e_ord', sa.Float(), nullable=True),
    sa.Column('n_ord', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('prdct_ver', sa.DateTime(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='schools'
    )
    op.create_index(op.f('ix_schools_schools_geom'), 'schools', ['geom'], unique=False, schema='schools')
    op.create_index(op.f('ix_schools_schools_id'), 'schools', ['id'], unique=False, schema='schools')
    op.create_index(op.f('ix_schools_schools_yishuv_symbol'), 'schools', ['yishuv_symbol'], unique=False, schema='schools')
    op.create_table('schools_with_description',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.Text(), nullable=True),
    sa.Column('students_number', sa.Integer(), nullable=True),
    sa.Column('municipality_name', sa.Text(), nullable=True),
    sa.Column('yishuv_name', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('inspection', sa.Text(), nullable=True),
    sa.Column('legal_status', sa.Text(), nullable=True),
    sa.Column('reporter', sa.Text(), nullable=True),
    sa.Column('geo_district', sa.Text(), nullable=True),
    sa.Column('education_type', sa.Text(), nullable=True),
    sa.Column('school_type', sa.Text(), nullable=True),
    sa.Column('institution_type', sa.Text(), nullable=True),
    sa.Column('lowest_grade', sa.Integer(), nullable=True),
    sa.Column('highest_grade', sa.Integer(), nullable=True),
    sa.Column('foundation_year', sa.Integer(), nullable=True),
    sa.Column('location_accuracy', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='schools'
    )
    op.create_index(op.f('ix_schools_schools_with_description_geom'), 'schools_with_description', ['geom'], unique=False, schema='schools')
    op.create_index(op.f('ix_schools_schools_with_description_id'), 'schools_with_description', ['id'], unique=False, schema='schools')
    op.create_index(op.f('ix_schools_schools_with_description_municipality_name'), 'schools_with_description', ['municipality_name'], unique=False, schema='schools')
    op.create_index(op.f('ix_schools_schools_with_description_school_id'), 'schools_with_description', ['school_id'], unique=False, schema='schools')
    op.create_index(op.f('ix_schools_schools_with_description_yishuv_name'), 'schools_with_description', ['yishuv_name'], unique=False, schema='schools')
    op.create_table('report_problem',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('signs_on_the_road_not_clear', sa.Boolean(), nullable=True),
    sa.Column('signs_problem', sa.Boolean(), nullable=True),
    sa.Column('pothole', sa.Boolean(), nullable=True),
    sa.Column('no_light', sa.Boolean(), nullable=True),
    sa.Column('no_sign', sa.Boolean(), nullable=True),
    sa.Column('crossing_missing', sa.Boolean(), nullable=True),
    sa.Column('sidewalk_is_blocked', sa.Boolean(), nullable=True),
    sa.Column('street_light_issue', sa.Boolean(), nullable=True),
    sa.Column('road_hazard', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('send_to_municipality', sa.Boolean(), nullable=True),
    sa.Column('image_data', sa.String(), nullable=True),
    sa.Column('personal_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='mobile_app'
    )
    op.create_index(op.f('ix_mobile_app_report_problem_id'), 'report_problem', ['id'], unique=False, schema='mobile_app')
    op.add_column('markers', sa.Column('accident_hour_raw', sa.Integer(), nullable=True))
    op.add_column('markers', sa.Column('accident_minute', sa.Integer(), nullable=True))
    op.add_column('markers', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('markers', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    op.add_column('markers', sa.Column('km_accurate', sa.Boolean(), nullable=True))
    op.add_column('markers', sa.Column('km_raw', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('mainStreet', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('non_urban_intersection_by_junction_number', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('non_urban_intersection_hebrew', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('provider_and_id', sa.BigInteger(), nullable=True))
    op.add_column('markers', sa.Column('provider_code', sa.Integer(), nullable=False))
    op.add_column('markers', sa.Column('secondaryStreet', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('street1_hebrew', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('street2_hebrew', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('markers', sa.Column('type', sa.Integer(), nullable=True))
    op.add_column('markers', sa.Column('vehicle_type_rsa', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('video_link', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('violation_type_rsa', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('yishuv_name', sa.Text(), nullable=True))
    op.create_index('acc_long_lat_idx', 'markers', ['latitude', 'longitude'], unique=False, schema='public')
    op.create_index('id_idx_markers', 'markers', ['id'], unique=False, schema='public')
    op.create_index('idx_markers_geom', 'markers', ['geom'], unique=False, schema='public')
    op.create_index(op.f('ix_public_markers_created'), 'markers', ['created'], unique=False, schema='public')
    op.create_index('provider_and_id_idx_markers', 'markers', ['provider_and_id'], unique=False, schema='public')
    op.drop_column('markers', 'street_sign')
    op.drop_column('markers', 'table_number')
    op.drop_column('markers', 'file_type')
    op.drop_column('markers', 'junction_name')
    op.drop_column('markers', 'sign')
    op.drop_column('markers', 'name')
    op.drop_column('markers', 'street_name')
    op.drop_column('markers', 'settlement')
    op.drop_column('markers', 'code')
    op.create_index(op.f('ix_public_waze_alerts_created_at'), 'waze_alerts', ['created_at'], unique=False, schema='public')
    op.drop_index('idx_waze_alerts_geom', table_name='waze_alerts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_waze_alerts_geom', 'waze_alerts', ['geom'], unique=False)
    op.drop_index(op.f('ix_public_waze_alerts_created_at'), table_name='waze_alerts', schema='public')
    op.add_column('markers', sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('settlement', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('street_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('sign', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('junction_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('file_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('table_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('street_sign', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('provider_and_id_idx_markers', table_name='markers', schema='public')
    op.drop_index(op.f('ix_public_markers_created'), table_name='markers', schema='public')
    op.drop_index('idx_markers_geom', table_name='markers', schema='public')
    op.drop_index('id_idx_markers', table_name='markers', schema='public')
    op.drop_index('acc_long_lat_idx', table_name='markers', schema='public')
    op.drop_column('markers', 'yishuv_name')
    op.drop_column('markers', 'violation_type_rsa')
    op.drop_column('markers', 'video_link')
    op.drop_column('markers', 'vehicle_type_rsa')
    op.drop_column('markers', 'type')
    op.drop_column('markers', 'title')
    op.drop_column('markers', 'street2_hebrew')
    op.drop_column('markers', 'street1_hebrew')
    op.drop_column('markers', 'secondaryStreet')
    op.drop_column('markers', 'provider_code')
    op.drop_column('markers', 'provider_and_id')
    op.drop_column('markers', 'non_urban_intersection_hebrew')
    op.drop_column('markers', 'non_urban_intersection_by_junction_number')
    op.drop_column('markers', 'mainStreet')
    op.drop_column('markers', 'longitude')
    op.drop_column('markers', 'latitude')
    op.drop_column('markers', 'km_raw')
    op.drop_column('markers', 'km_accurate')
    op.drop_column('markers', 'geom')
    op.drop_column('markers', 'description')
    op.drop_column('markers', 'created')
    op.drop_column('markers', 'address')
    op.drop_column('markers', 'accident_minute')
    op.drop_column('markers', 'accident_hour_raw')
    op.drop_index(op.f('ix_mobile_app_report_problem_id'), table_name='report_problem', schema='mobile_app')
    op.drop_table('report_problem', schema='mobile_app')
    op.drop_index(op.f('ix_schools_schools_with_description_yishuv_name'), table_name='schools_with_description', schema='schools')
    op.drop_index(op.f('ix_schools_schools_with_description_school_id'), table_name='schools_with_description', schema='schools')
    op.drop_index(op.f('ix_schools_schools_with_description_municipality_name'), table_name='schools_with_description', schema='schools')
    op.drop_index(op.f('ix_schools_schools_with_description_id'), table_name='schools_with_description', schema='schools')
    op.drop_index(op.f('ix_schools_schools_with_description_geom'), table_name='schools_with_description', schema='schools')
    op.drop_table('schools_with_description', schema='schools')
    op.drop_index(op.f('ix_schools_schools_yishuv_symbol'), table_name='schools', schema='schools')
    op.drop_index(op.f('ix_schools_schools_id'), table_name='schools', schema='schools')
    op.drop_index(op.f('ix_schools_schools_geom'), table_name='schools', schema='schools')
    op.drop_table('schools', schema='schools')
    op.drop_index(op.f('ix_schools_injured_around_school_all_data_school_id'), table_name='injured_around_school_all_data', schema='schools')
    op.drop_index(op.f('ix_schools_injured_around_school_all_data_id'), table_name='injured_around_school_all_data', schema='schools')
    op.drop_table('injured_around_school_all_data', schema='schools')
    op.drop_index(op.f('ix_schools_injured_around_school_school_yishuv_name'), table_name='injured_around_school', schema='schools')
    op.drop_index(op.f('ix_schools_injured_around_school_school_id'), table_name='injured_around_school', schema='schools')
    op.drop_index(op.f('ix_schools_injured_around_school_id'), table_name='injured_around_school', schema='schools')
    op.drop_table('injured_around_school', schema='schools')
    op.drop_table('news_flash', schema='news_flash')
    op.drop_index('provider_and_id_idx_vehicles', table_name='vehicles', schema='cbs')
    op.drop_index('accident_id_idx_vehicles', table_name='vehicles', schema='cbs')
    op.drop_table('vehicles', schema='cbs')
    op.drop_index('provider_and_id_idx_involved', table_name='involved', schema='cbs')
    op.drop_index('accident_id_idx_involved', table_name='involved', schema='cbs')
    op.drop_table('involved', schema='cbs')
    op.drop_index(op.f('ix_cbs_yishuv_shape_year'), table_name='yishuv_shape', schema='cbs')
    op.drop_index(op.f('ix_cbs_yishuv_shape_provider_code'), table_name='yishuv_shape', schema='cbs')
    op.drop_index(op.f('ix_cbs_yishuv_shape_id'), table_name='yishuv_shape', schema='cbs')
    op.drop_table('yishuv_shape', schema='cbs')
    op.drop_index(op.f('ix_cbs_weather_year'), table_name='weather', schema='cbs')
    op.drop_index(op.f('ix_cbs_weather_provider_code'), table_name='weather', schema='cbs')
    op.drop_index(op.f('ix_cbs_weather_id'), table_name='weather', schema='cbs')
    op.drop_table('weather', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_type_year'), table_name='vehicle_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_type_provider_code'), table_name='vehicle_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_type_id'), table_name='vehicle_type', schema='cbs')
    op.drop_table('vehicle_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_status_year'), table_name='vehicle_status', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_status_provider_code'), table_name='vehicle_status', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_status_id'), table_name='vehicle_status', schema='cbs')
    op.drop_table('vehicle_status', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_damage_year'), table_name='vehicle_damage', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_damage_provider_code'), table_name='vehicle_damage', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_damage_id'), table_name='vehicle_damage', schema='cbs')
    op.drop_table('vehicle_damage', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_attribution_year'), table_name='vehicle_attribution', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_attribution_provider_code'), table_name='vehicle_attribution', schema='cbs')
    op.drop_index(op.f('ix_cbs_vehicle_attribution_id'), table_name='vehicle_attribution', schema='cbs')
    op.drop_table('vehicle_attribution', schema='cbs')
    op.drop_index(op.f('ix_cbs_traffic_volume_id'), table_name='traffic_volume', schema='cbs')
    op.drop_table('traffic_volume', schema='cbs')
    op.drop_index(op.f('ix_cbs_traffic_light_year'), table_name='traffic_light', schema='cbs')
    op.drop_index(op.f('ix_cbs_traffic_light_provider_code'), table_name='traffic_light', schema='cbs')
    op.drop_index(op.f('ix_cbs_traffic_light_id'), table_name='traffic_light', schema='cbs')
    op.drop_table('traffic_light', schema='cbs')
    op.drop_index(op.f('ix_cbs_total_weight_year'), table_name='total_weight', schema='cbs')
    op.drop_index(op.f('ix_cbs_total_weight_provider_code'), table_name='total_weight', schema='cbs')
    op.drop_index(op.f('ix_cbs_total_weight_id'), table_name='total_weight', schema='cbs')
    op.drop_table('total_weight', schema='cbs')
    op.drop_index(op.f('ix_cbs_speed_limit_year'), table_name='speed_limit', schema='cbs')
    op.drop_index(op.f('ix_cbs_speed_limit_provider_code'), table_name='speed_limit', schema='cbs')
    op.drop_index(op.f('ix_cbs_speed_limit_id'), table_name='speed_limit', schema='cbs')
    op.drop_table('speed_limit', schema='cbs')
    op.drop_index(op.f('ix_cbs_sex_year'), table_name='sex', schema='cbs')
    op.drop_index(op.f('ix_cbs_sex_provider_code'), table_name='sex', schema='cbs')
    op.drop_index(op.f('ix_cbs_sex_id'), table_name='sex', schema='cbs')
    op.drop_table('sex', schema='cbs')
    op.drop_index(op.f('ix_cbs_safety_measures_use_year'), table_name='safety_measures_use', schema='cbs')
    op.drop_index(op.f('ix_cbs_safety_measures_use_provider_code'), table_name='safety_measures_use', schema='cbs')
    op.drop_index(op.f('ix_cbs_safety_measures_use_id'), table_name='safety_measures_use', schema='cbs')
    op.drop_table('safety_measures_use', schema='cbs')
    op.drop_index(op.f('ix_cbs_safety_measures_year'), table_name='safety_measures', schema='cbs')
    op.drop_index(op.f('ix_cbs_safety_measures_provider_code'), table_name='safety_measures', schema='cbs')
    op.drop_index(op.f('ix_cbs_safety_measures_id'), table_name='safety_measures', schema='cbs')
    op.drop_table('safety_measures', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_width_year'), table_name='road_width', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_width_provider_code'), table_name='road_width', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_width_id'), table_name='road_width', schema='cbs')
    op.drop_table('road_width', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_type_year'), table_name='road_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_type_provider_code'), table_name='road_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_type_id'), table_name='road_type', schema='cbs')
    op.drop_table('road_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_surface_year'), table_name='road_surface', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_surface_provider_code'), table_name='road_surface', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_surface_id'), table_name='road_surface', schema='cbs')
    op.drop_table('road_surface', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_sign_year'), table_name='road_sign', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_sign_provider_code'), table_name='road_sign', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_sign_id'), table_name='road_sign', schema='cbs')
    op.drop_table('road_sign', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_shape_year'), table_name='road_shape', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_shape_provider_code'), table_name='road_shape', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_shape_id'), table_name='road_shape', schema='cbs')
    op.drop_table('road_shape', schema='cbs')
    op.drop_table('road_segments', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_object_year'), table_name='road_object', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_object_provider_code'), table_name='road_object', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_object_id'), table_name='road_object', schema='cbs')
    op.drop_table('road_object', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_light_year'), table_name='road_light', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_light_provider_code'), table_name='road_light', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_light_id'), table_name='road_light', schema='cbs')
    op.drop_table('road_light', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_intactness_year'), table_name='road_intactness', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_intactness_provider_code'), table_name='road_intactness', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_intactness_id'), table_name='road_intactness', schema='cbs')
    op.drop_table('road_intactness', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_control_year'), table_name='road_control', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_control_provider_code'), table_name='road_control', schema='cbs')
    op.drop_index(op.f('ix_cbs_road_control_id'), table_name='road_control', schema='cbs')
    op.drop_table('road_control', schema='cbs')
    op.drop_index(op.f('ix_cbs_release_dest_year'), table_name='release_dest', schema='cbs')
    op.drop_index(op.f('ix_cbs_release_dest_provider_code'), table_name='release_dest', schema='cbs')
    op.drop_index(op.f('ix_cbs_release_dest_id'), table_name='release_dest', schema='cbs')
    op.drop_table('release_dest', schema='cbs')
    op.drop_index(op.f('ix_cbs_region_year'), table_name='region', schema='cbs')
    op.drop_index(op.f('ix_cbs_region_provider_code'), table_name='region', schema='cbs')
    op.drop_index(op.f('ix_cbs_region_id'), table_name='region', schema='cbs')
    op.drop_table('region', schema='cbs')
    op.drop_index(op.f('ix_cbs_provider_code_id'), table_name='provider_code', schema='cbs')
    op.drop_table('provider_code', schema='cbs')
    op.drop_index(op.f('ix_cbs_population_type_year'), table_name='population_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_population_type_provider_code'), table_name='population_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_population_type_id'), table_name='population_type', schema='cbs')
    op.drop_table('population_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_police_unit_year'), table_name='police_unit', schema='cbs')
    op.drop_index(op.f('ix_cbs_police_unit_provider_code'), table_name='police_unit', schema='cbs')
    op.drop_index(op.f('ix_cbs_police_unit_id'), table_name='police_unit', schema='cbs')
    op.drop_table('police_unit', schema='cbs')
    op.drop_index(op.f('ix_cbs_one_lane_year'), table_name='one_lane', schema='cbs')
    op.drop_index(op.f('ix_cbs_one_lane_provider_code'), table_name='one_lane', schema='cbs')
    op.drop_index(op.f('ix_cbs_one_lane_id'), table_name='one_lane', schema='cbs')
    op.drop_table('one_lane', schema='cbs')
    op.drop_index(op.f('ix_cbs_object_distance_year'), table_name='object_distance', schema='cbs')
    op.drop_index(op.f('ix_cbs_object_distance_provider_code'), table_name='object_distance', schema='cbs')
    op.drop_index(op.f('ix_cbs_object_distance_id'), table_name='object_distance', schema='cbs')
    op.drop_table('object_distance', schema='cbs')
    op.drop_index(op.f('ix_cbs_natural_area_year'), table_name='natural_area', schema='cbs')
    op.drop_index(op.f('ix_cbs_natural_area_provider_code'), table_name='natural_area', schema='cbs')
    op.drop_index(op.f('ix_cbs_natural_area_id'), table_name='natural_area', schema='cbs')
    op.drop_table('natural_area', schema='cbs')
    op.drop_index(op.f('ix_cbs_municipal_status_year'), table_name='municipal_status', schema='cbs')
    op.drop_index(op.f('ix_cbs_municipal_status_provider_code'), table_name='municipal_status', schema='cbs')
    op.drop_index(op.f('ix_cbs_municipal_status_id'), table_name='municipal_status', schema='cbs')
    op.drop_table('municipal_status', schema='cbs')
    op.drop_index(op.f('ix_cbs_multi_lane_year'), table_name='multi_lane', schema='cbs')
    op.drop_index(op.f('ix_cbs_multi_lane_provider_code'), table_name='multi_lane', schema='cbs')
    op.drop_index(op.f('ix_cbs_multi_lane_id'), table_name='multi_lane', schema='cbs')
    op.drop_table('multi_lane', schema='cbs')
    op.drop_index(op.f('ix_cbs_medical_type_year'), table_name='medical_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_medical_type_provider_code'), table_name='medical_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_medical_type_id'), table_name='medical_type', schema='cbs')
    op.drop_table('medical_type', schema='cbs')
    op.drop_index('provider_and_id_idx_markers', table_name='markers', schema='cbs')
    op.drop_index(op.f('ix_cbs_markers_geom'), table_name='markers', schema='cbs')
    op.drop_index(op.f('ix_cbs_markers_created'), table_name='markers', schema='cbs')
    op.drop_index('id_idx_markers', table_name='markers', schema='cbs')
    op.drop_index('acc_long_lat_idx', table_name='markers', schema='cbs')
    op.drop_table('markers', schema='cbs')
    op.drop_index(op.f('ix_cbs_location_accuracy_year'), table_name='location_accuracy', schema='cbs')
    op.drop_index(op.f('ix_cbs_location_accuracy_provider_code'), table_name='location_accuracy', schema='cbs')
    op.drop_index(op.f('ix_cbs_location_accuracy_id'), table_name='location_accuracy', schema='cbs')
    op.drop_table('location_accuracy', schema='cbs')
    op.drop_index(op.f('ix_cbs_late_deceased_year'), table_name='late_deceased', schema='cbs')
    op.drop_index(op.f('ix_cbs_late_deceased_provider_code'), table_name='late_deceased', schema='cbs')
    op.drop_index(op.f('ix_cbs_late_deceased_id'), table_name='late_deceased', schema='cbs')
    op.drop_table('late_deceased', schema='cbs')
    op.drop_index(op.f('ix_cbs_involved_type_year'), table_name='involved_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_involved_type_provider_code'), table_name='involved_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_involved_type_id'), table_name='involved_type', schema='cbs')
    op.drop_table('involved_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_injury_severity_year'), table_name='injury_severity', schema='cbs')
    op.drop_index(op.f('ix_cbs_injury_severity_provider_code'), table_name='injury_severity', schema='cbs')
    op.drop_index(op.f('ix_cbs_injury_severity_id'), table_name='injury_severity', schema='cbs')
    op.drop_table('injury_severity', schema='cbs')
    op.drop_index(op.f('ix_cbs_injured_type_year'), table_name='injured_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_injured_type_provider_code'), table_name='injured_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_injured_type_id'), table_name='injured_type', schema='cbs')
    op.drop_table('injured_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_injured_position_year'), table_name='injured_position', schema='cbs')
    op.drop_index(op.f('ix_cbs_injured_position_provider_code'), table_name='injured_position', schema='cbs')
    op.drop_index(op.f('ix_cbs_injured_position_id'), table_name='injured_position', schema='cbs')
    op.drop_table('injured_position', schema='cbs')
    op.drop_index(op.f('ix_cbs_hospital_time_year'), table_name='hospital_time', schema='cbs')
    op.drop_index(op.f('ix_cbs_hospital_time_provider_code'), table_name='hospital_time', schema='cbs')
    op.drop_index(op.f('ix_cbs_hospital_time_id'), table_name='hospital_time', schema='cbs')
    op.drop_table('hospital_time', schema='cbs')
    op.drop_index(op.f('ix_cbs_geo_area_year'), table_name='geo_area', schema='cbs')
    op.drop_index(op.f('ix_cbs_geo_area_provider_code'), table_name='geo_area', schema='cbs')
    op.drop_index(op.f('ix_cbs_geo_area_id'), table_name='geo_area', schema='cbs')
    op.drop_table('geo_area', schema='cbs')
    op.drop_index(op.f('ix_cbs_engine_volume_year'), table_name='engine_volume', schema='cbs')
    op.drop_index(op.f('ix_cbs_engine_volume_provider_code'), table_name='engine_volume', schema='cbs')
    op.drop_index(op.f('ix_cbs_engine_volume_id'), table_name='engine_volume', schema='cbs')
    op.drop_table('engine_volume', schema='cbs')
    op.drop_index(op.f('ix_cbs_driving_directions_year'), table_name='driving_directions', schema='cbs')
    op.drop_index(op.f('ix_cbs_driving_directions_provider_code'), table_name='driving_directions', schema='cbs')
    op.drop_index(op.f('ix_cbs_driving_directions_id'), table_name='driving_directions', schema='cbs')
    op.drop_table('driving_directions', schema='cbs')
    op.drop_index(op.f('ix_cbs_district_year'), table_name='district', schema='cbs')
    op.drop_index(op.f('ix_cbs_district_provider_code'), table_name='district', schema='cbs')
    op.drop_index(op.f('ix_cbs_district_id'), table_name='district', schema='cbs')
    op.drop_table('district', schema='cbs')
    op.drop_index(op.f('ix_cbs_discussions_geom'), table_name='discussions', schema='cbs')
    op.drop_index(op.f('ix_cbs_discussions_created'), table_name='discussions', schema='cbs')
    op.drop_index('disc_long_lat_idx', table_name='discussions', schema='cbs')
    op.drop_table('discussions', schema='cbs')
    op.drop_index(op.f('ix_cbs_didnt_cross_year'), table_name='didnt_cross', schema='cbs')
    op.drop_index(op.f('ix_cbs_didnt_cross_provider_code'), table_name='didnt_cross', schema='cbs')
    op.drop_index(op.f('ix_cbs_didnt_cross_id'), table_name='didnt_cross', schema='cbs')
    op.drop_table('didnt_cross', schema='cbs')
    op.drop_index(op.f('ix_cbs_day_type_year'), table_name='day_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_day_type_provider_code'), table_name='day_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_day_type_id'), table_name='day_type', schema='cbs')
    op.drop_table('day_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_day_night_year'), table_name='day_night', schema='cbs')
    op.drop_index(op.f('ix_cbs_day_night_provider_code'), table_name='day_night', schema='cbs')
    op.drop_index(op.f('ix_cbs_day_night_id'), table_name='day_night', schema='cbs')
    op.drop_table('day_night', schema='cbs')
    op.drop_index(op.f('ix_cbs_day_in_week_year'), table_name='day_in_week', schema='cbs')
    op.drop_index(op.f('ix_cbs_day_in_week_provider_code'), table_name='day_in_week', schema='cbs')
    op.drop_index(op.f('ix_cbs_day_in_week_id'), table_name='day_in_week', schema='cbs')
    op.drop_table('day_in_week', schema='cbs')
    op.drop_index(op.f('ix_cbs_cross_mode_year'), table_name='cross_mode', schema='cbs')
    op.drop_index(op.f('ix_cbs_cross_mode_provider_code'), table_name='cross_mode', schema='cbs')
    op.drop_index(op.f('ix_cbs_cross_mode_id'), table_name='cross_mode', schema='cbs')
    op.drop_table('cross_mode', schema='cbs')
    op.drop_index(op.f('ix_cbs_cross_location_year'), table_name='cross_location', schema='cbs')
    op.drop_index(op.f('ix_cbs_cross_location_provider_code'), table_name='cross_location', schema='cbs')
    op.drop_index(op.f('ix_cbs_cross_location_id'), table_name='cross_location', schema='cbs')
    op.drop_table('cross_location', schema='cbs')
    op.drop_index(op.f('ix_cbs_cross_direction_year'), table_name='cross_direction', schema='cbs')
    op.drop_index(op.f('ix_cbs_cross_direction_provider_code'), table_name='cross_direction', schema='cbs')
    op.drop_index(op.f('ix_cbs_cross_direction_id'), table_name='cross_direction', schema='cbs')
    op.drop_table('cross_direction', schema='cbs')
    op.drop_index(op.f('ix_cbs_columns_description_year'), table_name='columns_description', schema='cbs')
    op.drop_index(op.f('ix_cbs_columns_description_provider_code'), table_name='columns_description', schema='cbs')
    op.drop_index(op.f('ix_cbs_columns_description_id'), table_name='columns_description', schema='cbs')
    op.drop_table('columns_description', schema='cbs')
    op.drop_table('cities_vehicles_registered', schema='cbs')
    op.drop_table('cities', schema='cbs')
    op.drop_index(op.f('ix_cbs_age_group_year'), table_name='age_group', schema='cbs')
    op.drop_index(op.f('ix_cbs_age_group_provider_code'), table_name='age_group', schema='cbs')
    op.drop_index(op.f('ix_cbs_age_group_id'), table_name='age_group', schema='cbs')
    op.drop_table('age_group', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_type_year'), table_name='accident_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_type_provider_code'), table_name='accident_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_type_id'), table_name='accident_type', schema='cbs')
    op.drop_table('accident_type', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_severity_year'), table_name='accident_severity', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_severity_provider_code'), table_name='accident_severity', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_severity_id'), table_name='accident_severity', schema='cbs')
    op.drop_table('accident_severity', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_month_year'), table_name='accident_month', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_month_provider_code'), table_name='accident_month', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_month_id'), table_name='accident_month', schema='cbs')
    op.drop_table('accident_month', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_hour_raw_year'), table_name='accident_hour_raw', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_hour_raw_provider_code'), table_name='accident_hour_raw', schema='cbs')
    op.drop_index(op.f('ix_cbs_accident_hour_raw_id'), table_name='accident_hour_raw', schema='cbs')
    op.drop_table('accident_hour_raw', schema='cbs')
    # ### end Alembic commands ###
