"""Adding postgis extension

Revision ID: 5a5ffe56bb7
Revises: f67d98a989e7
Create Date: 2020-02-01

"""
# revision identifiers, used by Alembic.
revision = '5a5ffe56bb7'
down_revision = 'f67d98a989e7'
branch_labels = None
depends_on = None

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute('CREATE EXTENSION IF NOT EXISTS postgis;')
    conn.execute('CREATE EXTENSION IF NOT EXISTS postgis_topology;')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute('DROP EXTENSION postgis_topology;')
    conn.execute('DROP EXTENSION postgis;')
    conn.execute('DROP SCHEMA IF EXISTS topology CASCADE;')
    ### end Alembic commands ###
