"""added WazeTrafficJams model

Revision ID: dabf008b4de0
Revises: 687465b3b8f1
Create Date: 2020-02-08 11:44:32.830328

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision = 'dabf008b4de0'
down_revision = '687465b3b8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waze_trafic_jams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('line', sa.Text(), nullable=True),
    sa.Column('speed_kmh', sa.Integer(), nullable=True),
    sa.Column('turn_type', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('segments', sa.Text(), nullable=True),
    sa.Column('road_type', sa.Integer(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('end_node', sa.Text(), nullable=True),
    sa.Column('blocking_alert_uuid', sa.Text(), nullable=True),
    sa.Column('start_node', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waze_trafic_jams_created_at'), table_name='waze_trafic_jams')
    op.drop_table('waze_trafic_jams')
    # ### end Alembic commands ###
