from anyway.core.database import SchoolshBase
from sqlalchemy import Column, BigInteger, Integer, String, Boolean, Float, ForeignKey, DateTime, Text, Index, desc, \
    sql, Table, \
    ForeignKeyConstraint, func, and_, TIMESTAMP
from geoalchemy2 import Geometry

class School(SchoolshBase):
    __tablename__ = "schools"
    id = Column(BigInteger(), primary_key=True, index=True)
    fcode_type = Column(Integer(), nullable=True)
    yishuv_symbol = Column(Integer(), nullable=True, index=True)
    yishuv_name = Column(Text(), nullable=True)
    school_name = Column(Text(), nullable=True)
    school_latin_name = Column(Text(), nullable=True)
    usg = Column(Integer(), nullable=True)
    usg_code = Column(Integer(), nullable=True)
    e_ord = Column(Float(), nullable=True)
    n_ord = Column(Float(), nullable=True)
    longitude = Column(Float(), nullable=True)
    latitude = Column(Float(), nullable=True)
    geom = Column(Geometry('POINT', srid=4326), index=True)
    data_year = Column(Integer(), nullable=True)
    prdct_ver = Column(DateTime, default=None)
    x = Column(Float(), nullable=True)
    y = Column(Float(), nullable=True)


class SchoolWithDescription(SchoolshBase):
    __tablename__ = "schools_with_description"
    id = Column(BigInteger(), autoincrement=True, primary_key=True, index=True)
    data_year = Column(Integer(), nullable=True)
    school_id = Column(Integer(), nullable=True, index=True)
    school_name = Column(Text(), nullable=True)
    students_number = Column(Integer(), nullable=True)
    municipality_name = Column(Text(), nullable=True, index=True)
    yishuv_name = Column(Text(), nullable=True, index=True)
    sector = Column(Text(), nullable=True)
    inspection = Column(Text(), nullable=True)
    legal_status = Column(Text(), nullable=True)
    reporter = Column(Text(), nullable=True)
    geo_district = Column(Text(), nullable=True)
    education_type = Column(Text(), nullable=True)
    school_type = Column(Text(), nullable=True)
    institution_type = Column(Text(), nullable=True)
    lowest_grade = Column(Integer(), nullable=True)
    highest_grade = Column(Integer(), nullable=True)
    foundation_year = Column(Integer(), nullable=True)
    location_accuracy = Column(Text(), nullable=True)
    geom = Column(Geometry('POINT', srid=4326), index=True)
    x = Column(Float(), nullable=True)
    y = Column(Float(), nullable=True)
    longitude = Column(Float(), nullable=True)
    latitude = Column(Float(), nullable=True)


class InjuredAroundSchool(SchoolshBase):
    __tablename__ = "injured_around_school"
    id = Column(BigInteger(), autoincrement=True, primary_key=True, index=True)
    school_id = Column(Integer(), nullable=True, index=True)
    school_name = Column(Text(), nullable=True)
    school_type = Column(Text(), nullable=True)
    school_longitude = Column(Float(), nullable=True)
    school_latitude = Column(Float(), nullable=True)
    school_yishuv_name = Column(Text(), nullable=True, index=True)
    school_anyway_link = Column(Text(), nullable=True)
    accident_year = Column(Integer(), nullable=True)
    distance_in_km = Column(Float(), nullable=True)
    killed_count = Column(Integer(), nullable=True)
    severly_injured_count = Column(Integer(), nullable=True)
    light_injured_count = Column(Integer(), nullable=True)
    total_injured_killed_count = Column(Integer(), nullable=True)
    rank_in_yishuv = Column(Integer(), nullable=True)


class InjuredAroundSchoolAllData(SchoolshBase):
    __tablename__ = "injured_around_school_all_data"
    id = Column(BigInteger(), autoincrement=True, primary_key=True, index=True)
    school_id = Column(Float(), nullable=False, index=True)
    markers_provider_and_id = Column(BigInteger())
    markers_provider_code = Column(Float())
    markers_description = Column(Text())
    markers_accident_type = Column(Float())
    markers_accident_severity = Column(Float())
    markers_address = Column(Text())
    markers_location_accuracy = Column(Float())
    markers_road_type = Column(Float())
    markers_road_shape = Column(Float())
    markers_day_type = Column(Float())
    markers_police_unit = Column(Float())
    markers_mainStreet = Column(Text())
    markers_secondaryStreet = Column(Text())
    markers_junction = Column(Text())
    markers_one_lane = Column(Float())
    markers_multi_lane = Column(Float())
    markers_speed_limit = Column(Float())
    markers_road_intactness = Column(Float())
    markers_road_width = Column(Float())
    markers_road_sign = Column(Float())
    markers_road_light = Column(Float())
    markers_road_control = Column(Float())
    markers_weather = Column(Float())
    markers_road_surface = Column(Float())
    markers_road_object = Column(Float())
    markers_object_distance = Column(Float())
    markers_didnt_cross = Column(Float())
    markers_cross_mode = Column(Float())
    markers_cross_location = Column(Float())
    markers_cross_direction = Column(Float())
    markers_video_link = Column(Text())
    markers_road1 = Column(Float())
    markers_road2 = Column(Float())
    markers_km = Column(Float())
    markers_yishuv_symbol = Column(Float())
    markers_yishuv_name = Column(Text())
    markers_geo_area = Column(Float())
    markers_day_night = Column(Float())
    markers_day_in_week = Column(Float())
    markers_traffic_light = Column(Float())
    markers_region = Column(Float())
    markers_district = Column(Float())
    markers_natural_area = Column(Float())
    markers_municipal_status = Column(Float())
    markers_yishuv_shape = Column(Float())
    markers_street1 = Column(Float())
    markers_street1_hebrew = Column(Text())
    markers_street2 = Column(Float())
    markers_street2_hebrew = Column(Text())
    markers_house_number = Column(Float())
    markers_urban_intersection = Column(Float())
    markers_non_urban_intersection = Column(Float())
    markers_non_urban_intersection_hebrew = Column(Text())
    markers_accident_year = Column(Float())
    markers_accident_month = Column(Float())
    markers_accident_day = Column(Float())
    markers_accident_hour_raw = Column(Float())
    markers_accident_hour = Column(Float())
    markers_accident_minute = Column(Float())
    markers_x = Column(Float())
    markers_y = Column(Float())
    markers_vehicle_type_rsa = Column(Text())
    markers_violation_type_rsa = Column(Text())
    markers_geom = Column(Geometry('POINT'))
    involved_provider_and_id = Column(BigInteger())
    involved_provider_code = Column(Float())
    involved_accident_id = Column(BigInteger())
    involved_involved_type = Column(Float())
    involved_license_acquiring_date = Column(Float())
    involved_age_group = Column(Float())
    involved_sex = Column(Float())
    involved_vehicle_type = Column(Float())
    involved_safety_measures = Column(Float())
    involved_involve_yishuv_symbol = Column(Float())
    involved_involve_yishuv_name = Column(Text())
    involved_injury_severity = Column(Float())
    involved_injured_type = Column(Float())
    involved_injured_position = Column(Float())
    involved_population_type = Column(Float())
    involved_home_region = Column(Float())
    involved_home_district = Column(Float())
    involved_home_natural_area = Column(Float())
    involved_home_municipal_status = Column(Float())
    involved_home_yishuv_shape = Column(Float())
    involved_hospital_time = Column(Float())
    involved_medical_type = Column(Float())
    involved_release_dest = Column(Float())
    involved_safety_measures_use = Column(Float())
    involved_late_deceased = Column(Float())
    involved_car_id = Column(Float())
    involved_involve_id = Column(Float())
    involved_accident_year = Column(Float())
    involved_accident_month = Column(Float())
    involved_injury_severity_mais = Column(Float())
